---
title: "Quadvariate Viz"
---

Use this file to generate a professional looking **quadvariate** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.



```{r}
library(tidyverse)
```


```{r}
# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  
```

```{r}
 #| fig-cap: For all three locations in Austrailia, there is a positive relationship between temperature at 9am and temperature at 3pm. This relationship is steeper on days where it rains. 
 
 #| fig-alt: This is a faceted scatter plot where the x axis is temperature at 9am and the y axis is temperature at 3pm. Each facet represents wheather or not it rained today -- the leftmost facet is for the days it didn't rain, the next facet is for the days it did rain, and the last facet is for days where the rain data is not avaialable. The dots of the scatter plot are color coded by location: Hobart, Uluru, and Wollongong. For all three locations, there is a positive relationship between temperature at 9am and temperature at 3pm. This relationship is steeper on days where it rains. 


  
ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point() +
  facet_wrap(~ raintoday) +
  scale_color_viridis_d()+
labs(x = "Temperature at 9a.m.", y = "Temperature at 3p.m.", title = "Temperature at 3p.m. vs Temperature at 9a.m.", subtitle = "How do daily temperatures vary by location?")
```

