---
title: "soloProject"
format: html
---

#install packages
```{r}
library(sf)
library(ggplot2)
library(tidyverse)
```

#download shape file
```{r}
minnesota <- read_sf("~/Downloads/stat 112/tl_2023_27_tract/tl_2023_27_tract.shp")
```


#map the plot
```{r}
ggplot() +
  geom_sf(data = minnesota)
```

#load in population data
```{r}
population_data <- read_csv("~/Downloads/stat 112/data/mn_county_population_data.csv")
```

#load in data set with FPS codes and county name to link the shp file "minnesota" (FPS code) with "poulation_data" (county name)
```{r}
fps_codes <- read_csv("~/Downloads/stat 112/data/county_fips_master.csv")
```

#clean fps_codes data 
```{r}
#filter MN and clean the fps codes
fps_codes_clean  <- fps_codes |> 
   filter(state_name == "Minnesota") |>
   mutate (fps_new = as.character(fips)) |>
   mutate (fps_new = str_sub(fps_new, 3)) |>
   mutate(long_name = str_replace(long_name, " County MN", ""))

```


#join the fps clean data with minnesota shp file
```{r}
fpsAndMinnesota  <- minnesota |> 
  select(geometry, COUNTYFP) |> 
  left_join(fps_codes_clean |>  
              select(fps_new, county_name), join_by(COUNTYFP == fps_new))
  

```

#join the population_data with the fpsAndMinnesota
```{r}
populationFpsAndMinnesota <-fpsAndMinnesota |>
  mutate(county_name = str_replace(county_name, " County", "")) |>
  left_join (population_data |> 
               select(Population,`Geography Name`),
               join_by (county_name ==`Geography Name`)) 
```



```{r}
#| fig-cap: "Population of Minnesota is highest where Minnespolis and St. Paul (the biggest cities) are."
#| fig-alt: "This is a map of MInnesota. There is a higher population in the center and eastern part of the state.The population in this area is around 1,000,000.  There are four locations with a population of around 200,000-350,000. These are in the southern, center, northern part of the state, and the area surrounding the twin cities and their suburbs. Everywhere else has a population less than 200,000. "
ggplot() + 
  geom_sf(data = populationFpsAndMinnesota,aes(fill = Population)) + 
  scale_fill_viridis_c()+
  labs( title = "Population of Minnesota") 



```



#analysis
```{r}
#There is a higher population in the center and eastern part of the state. This is because the two biggest cities of the state are here: Minneapolis and St. Paul. The high population counts also come from the surrounding suburbs. The population in this area is around 1,000,000. 

#There are four locations with a population of around 200,000-350,000. These are in the southern, center, northern part of the state, and the area surrounding the twin cities and their suburbs. The southern location is home to Rochester, which houses Mayo Clinic, a world-renowned medical center, and UMN Rochester, a public university. The northern part is a section of the MN iron range. A lot of people might have come here for mining jobs and other iron-related work. The part in the center is where St. Cloud is. St. Cloud houses a big public university -- St. Cloud State, and is home to several businesses. It is more urban relative to the places that surround it. Everywhere else has a population less than 200,000. These areas are rural/farmlands (especially in the sourthern and western part of the state), or heavily forested (especially in ther north and northeastern part of the state).
```



